Docs:
  - docs/*
  - docs/_static/*
  - docs/_templates/*
  - docs/whatsnew/*
  - .mailmap
  - readthedocs.yml
  - any: ['*.rst', '!CHANGES.rst']

testing:
  - codecov.yml
  - conftest.py
  - '**/conftest.py'
  - tox.ini
  - .github/**/*.yml
  - .pep8speaks.yml

installation:
  - docs/install.rst
  - libs/**/*/pyproject.toml
  - setup.*

core:
  - libs/core/*
  - libs/core/*
  - docs/libs/core/*
