name: Cron CI

on:
  schedule:
    - cron: "0 10 * * 1"  # Mondays @ 6AM Eastern
  pull_request:
    # We also want this workflow triggered if the 'Extra CI' label is added
    # or present when PR is updated
    types:
      - synchronize
      - labeled

jobs:
  tests:
    name: Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: (github.event_name == 'schedule' || contains(github.event.pull_request.labels.*.name, 'Extra CI'))
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest] # TODO: re-enable windows-latest
        python: [3.8, 3.9, 3.10]
        include:
          # These set options for each python version. So, for example, when any
          # python 3.10 job in the matrix runs, it should use this toxenv
          - python: 3.10
            toxenv: py310-test-cov

          - python: 3.9
            toxenv: py39-test-cov

          - python: 3.8
            toxenv: py38-test-alldeps

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Python dependencies
        run: python -m pip install --upgrade tox codecov

      - name: Run tests
        run: tox ${{ matrix.toxargs }} -e ${{ matrix.toxenv }} -- ${{ matrix.toxposargs }}
