name: CI

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:

  # Allowed to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  initial_checks:
    name: Mandatory checks before CI
    runs-on: ubuntu-latest
    steps:
    - name: Check base branch
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        script: |
          const skip_label = 'skip-basebranch-check';
          const { default_branch: allowed_basebranch } = context.payload.repository;
          const pr = context.payload.pull_request;
          if (pr.labels.find(lbl => lbl.name === skip_label)) {
            core.info(`Base branch check is skipped due to the presence of ${skip_label} label`);
            return;
          }
          if (pr.base.ref !== allowed_basebranch) {
            core.setFailed(`PR opened against ${pr.base.ref}, not ${allowed_basebranch}`);
          } else {
            core.info(`PR opened correctly against ${allowed_basebranch}`);
          }

  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:

          - name: Python 3.10 with minimal dependencies and coverage
            os: ubuntu-latest
            python: '3.10'
            toxenv: py310-test-cov

          - name: Python 3.9 with all optional dependencies
            os: ubuntu-latest
            python: 3.9
            toxenv: py39-test-alldeps

          - name: Python 3.8 with oldest supported version of all dependencies
            os: ubuntu-latest
            python: 3.8
            toxenv: py38-test-oldestdeps

          # Mac and Windows:
          - name: Python 3.9 standard tests (macOS)
            os: macos-latest
            python: 3.9
            toxenv: py39-test

          - name: Python 3.9 standard tests (Windows)
            os: windows-latest
            python: 3.9
            toxenv: py39-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Current Pull Request
        uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: pr
        with:
          github-token: ${{ github.token }}
          filterOutClosed: true

      - name: Set up Python on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install Python dependencies
        run: python -m pip install --upgrade tox codecov

      - name: Get changed files - infrastructure
        id: changed-files-infrastructure
        uses: tj-actions/changed-files@v34.5.0
        with:
          use_fork_point: "true"
          files: |
            .github/workflows/ci-*.yml
            pre-commit-config.yaml
            pyproject.toml
            tests/tox.ini

      # ------ CORE ------

      - name: Get changed files - core
        id: changed-files-core
        uses: tj-actions/changed-files@v34.5.0
        with:
          use_fork_point: "true"
          files: |
            libs/core
            docs/libs/core

      - name: Run tests - core
        if: steps.changed-files-infrastructure.outputs.any_modified || steps.changed-files-core.outputs.any_modified == 'true'
        working-directory: ./libs/core
        run: tox ${{ matrix.toxargs }} -c ../../tests/tox.ini -e ${{ matrix.toxenv }} -- ${{ matrix.toxposargs }}

      # ------------------

      - name: Upload coverage report to codecov
        if: ${{ contains(matrix.toxenv,'-cov') }}
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
