name: "When Opened"

on:
  issues:
    types:
    - opened
  pull_request_target:
    types:
    - opened

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    # NOTE: sync-labels due to https://github.com/actions/labeler/issues/112
    - name: Label PR
      uses: actions/labeler@v5
      if: github.event_name == 'pull_request_target' && github.event.pull_request.user.login != 'meeseeksmachine'
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: ''
